---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by WJ.
--- DateTime: 2024/10/23 16:37
--- 消息队列实现优惠券秒杀资格判断
-- 1.参数列表 优惠券ID 用户ID 订单ID
local voucherId=ARGV[1]
local userId=ARGV[2]
local orderId = ARGV[3]

-- 2.存储到Redis的key 库存key 订单key
local stockKey='seckill:stock:' .. voucherId
local orderKey='seckill:order:' .. voucherId

-- 3.判断库存是否充足
if(tonumber(redis.call('GET',stockKey)) <= 0) then
    -- 库存不足则返回1
    return 1
end

--4.判断用户是否下单过 实现一人一单 SISMEMBER(set集合) orderKey userId
if(redis.call('sismember',orderKey,userId) == 1) then
    return 2
end

--5.可以下单，扣减库存
redis.call('incrby',stockKey,-1)

--6.记录下单用户,保存到set集合中
redis.call('sadd',orderKey,userId)
--7.将下单数据保存到消息队列中
redis.call("xadd", 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)

-- 8.最终成功下单，返回0
return 0
